name: run unit- and integration tests

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - feature/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: yarn install + test:ci
      run: |
        yarn install
        yarn test:ci  
